language: c
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential subversion uuid-dev iasl nasm gcc-4.9
script:
  - make -C BaseTools
  - export EDK_TOOLS_PATH=$(pwd -P)/BaseTools
  - . edksetup.sh BaseTools
  - sed 's/^ACTIVE_PLATFORM.*/ACTIVE_PLATFORM=Clover\/Clover.dsc/g' -i $WORKSPACE/Conf/target.txt
  - sed 's/^TOOL_CHAIN_TAG.*/TOOL_CHAIN_TAG=GCC46/g' -i $WORKSPACE/Conf/target.txt
  - sed 's/^TARGET_ARCH.*/TARGET_ARCH=IA32 X64/g' -i $WORKSPACE/Conf/target.txt
  - build
